# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/impostor.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/impostor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/impostor.proto\x12\x0bimpostor.v1\"\x9d\x01\n\x10UtteranceRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x12\n\npersona_id\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\x12%\n\x07history\x18\x04 \x03(\x0b\x32\x14.impostor.v1.Message\x12-\n\x06\x63onfig\x18\x05 \x01(\x0b\x32\x1d.impostor.v1.GenerationConfig\"5\n\x07Message\x12\r\n\x05\x61lias\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05ts_ms\x18\x03 \x01(\x03\"\x92\x01\n\x10GenerationConfig\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\r\n\x05top_p\x18\x02 \x01(\x02\x12\x11\n\tmax_words\x18\x03 \x01(\x05\x12\x1d\n\x15system_prompt_version\x18\x04 \x01(\t\x12\x16\n\x0e\x65ngine_backend\x18\x05 \x01(\t\x12\x10\n\x08model_id\x18\x06 \x01(\t\"K\n\x0eUtteranceChunk\x12\x12\n\ntext_delta\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x13\n\x0btoken_index\x18\x03 \x01(\x05\"\x0f\n\rHealthRequest\"C\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t2\xab\x01\n\x0eImpostorEngine\x12Q\n\x11GenerateUtterance\x12\x1d.impostor.v1.UtteranceRequest\x1a\x1b.impostor.v1.UtteranceChunk0\x01\x12\x46\n\x0bHealthCheck\x12\x1a.impostor.v1.HealthRequest\x1a\x1b.impostor.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.impostor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UTTERANCEREQUEST']._serialized_start=38
  _globals['_UTTERANCEREQUEST']._serialized_end=195
  _globals['_MESSAGE']._serialized_start=197
  _globals['_MESSAGE']._serialized_end=250
  _globals['_GENERATIONCONFIG']._serialized_start=253
  _globals['_GENERATIONCONFIG']._serialized_end=399
  _globals['_UTTERANCECHUNK']._serialized_start=401
  _globals['_UTTERANCECHUNK']._serialized_end=476
  _globals['_HEALTHREQUEST']._serialized_start=478
  _globals['_HEALTHREQUEST']._serialized_end=493
  _globals['_HEALTHRESPONSE']._serialized_start=495
  _globals['_HEALTHRESPONSE']._serialized_end=562
  _globals['_IMPOSTORENGINE']._serialized_start=565
  _globals['_IMPOSTORENGINE']._serialized_end=736
# @@protoc_insertion_point(module_scope)
