# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import impostor_pb2 as proto_dot_impostor__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/impostor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImpostorEngineStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateUtterance = channel.unary_stream(
                '/impostor.v1.ImpostorEngine/GenerateUtterance',
                request_serializer=proto_dot_impostor__pb2.UtteranceRequest.SerializeToString,
                response_deserializer=proto_dot_impostor__pb2.UtteranceChunk.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/impostor.v1.ImpostorEngine/HealthCheck',
                request_serializer=proto_dot_impostor__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_impostor__pb2.HealthResponse.FromString,
                _registered_method=True)


class ImpostorEngineServicer:
    """Missing associated documentation comment in .proto file."""

    def GenerateUtterance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImpostorEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateUtterance': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateUtterance,
                    request_deserializer=proto_dot_impostor__pb2.UtteranceRequest.FromString,
                    response_serializer=proto_dot_impostor__pb2.UtteranceChunk.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_impostor__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_impostor__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'impostor.v1.ImpostorEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('impostor.v1.ImpostorEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImpostorEngine:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateUtterance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/impostor.v1.ImpostorEngine/GenerateUtterance',
            proto_dot_impostor__pb2.UtteranceRequest.SerializeToString,
            proto_dot_impostor__pb2.UtteranceChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/impostor.v1.ImpostorEngine/HealthCheck',
            proto_dot_impostor__pb2.HealthRequest.SerializeToString,
            proto_dot_impostor__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
